inherit_from: ./configs/local/TUM_RGBD/tum.yaml

scene: freiburg1_rpy
only_tracking: False
wandb: False

data:
  input_folder: datasets/TUM_RGBD/rgbd_dataset_freiburg1_rpy
cam:
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]
